export const REQUEST_API_LIST_TO_DO = 'REQUEST_API_LIST_TO_DO';
export const RECEIVE_API_PRODUCT_LIST_TO_DO = 'RECEIVE_API_PRODUCT_LIST_TO_DO';
export const RECEIVE_API_PRODUCT_LIST_TO_DO_SUCCESS ='RECEIVE_API_PRODUCT_LIST_TO_DO_SUCCESS';